all: project_1 project_2 project_2c project_3 project_4 project_5 project_6 project_7 project_8 project_9 project_10 project_11 project_12 project_13 project_14 project_15 project_16 project_17 project_18

project_1:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_1 project_1.c

project_2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_2 project_2.c

project_2c:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_2c project_2c.c

project_3:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_3 project_3.c

project_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_4 project_4.c

project_5:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_5 project_5.c

project_6:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_6 project_6.c

project_7:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_7 project_7.c

project_8:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_8 project_8.c

project_9:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_9 project_9.c

project_10:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_10 project_10.c

project_11:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_11 project_11.c

project_12:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_12 project_12.c

project_13:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_13 project_13.c

project_14:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_14 project_14.c

project_15:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_15 project_15.c

project_16:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_16 project_16.c

project_17:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_17 project_17.c

project_18:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_18 project_18.c

clean:
	rm project_1 project_2 project_2c project_3 project_4 project_5 project_6 project_7 project_8 project_9 project_10 project_11 project_12 project_13 project_14 project_15 project_16 project_17 project_18
