all: exercise_1 exercise_2 exercise_3 exercise_4 exercise_5

exercise_1: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_1 exercise_1.c

exercise_2: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_2 exercise_2.c

exercise_3: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_3 exercise_3.c

exercise_4: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_4 exercise_4.c

exercise_5: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_5 exercise_5.c

clean:
	rm exercise_1 exercise_2 exercise_3 exercise_4 exercise_5