CC=gcc
CFLAGS=-O -Wall -W -pedantic -ansi -std=c99
MEM_LEAKS=-fsanitize=address

all: exercise_4 exercise_6 exercise_8 exercise_9 exercise_10 exercise_11 exercise_12 exercise_13

exercise_4: exercise_4.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_6: exercise_6.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_8: exercise_8.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_9: exercise_9.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_10: exercise_10.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_11: exercise_11.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_12: exercise_12.c
	$(CC) $(CFLAGS) -o $@ $<

exercise_13: exercise_13.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm exercise_4 exercise_6 exercise_8 exercise_9 exercise_10 exercise_11 exercise_12 exercise_13
