all: exercise_3 exercise_4 exercise_5 exercise_6 exercise_7 exercise_8

exercise_3:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_3 exercise_3.c

exercise_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_4 exercise_4.c

exercise_5:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_5 exercise_5.c

exercise_6:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_6 exercise_6.c

exercise_7:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_7 exercise_7.c

exercise_8:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_8 exercise_8.c

clean:
	rm exercise_3 exercise_4 exercise_5 exercise_6 exercise_7 exercise_8
