all: exercise_1 exercise_2 exercise_6

exercise_1: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_1 exercise_1.c

exercise_2: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_2 exercise_2.c

exercise_6: 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_6 exercise_6.c

clean:
	rm exercise_1 exercise_2 exercise_6