all: exercise_1 exercise_2 exercise_3 exercise_4 exercise_11

exercise_1:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_1 exercise_1.c

exercise_2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_2 exercise_2.c
	
exercise_3:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_3 exercise_3.c

exercise_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_4 exercise_4.c

exercise_11:
	gcc -O -Wall -W -Wextra -pedantic -ansi -std=c99 -o exercise_11 exercise_11.c

clean:
	rm exercise_1 exercise_2 exercise_3 exercise_4 exercise_11