CC=gcc
CFLAGS=-O -Wall -W -pedantic -ansi -std=c99

# $@ represents the target, while $< represents the first prerequisite
# In this context, for instance
# 	exercise_1: exercise_1.c
# 		<command>
# exercise_1 is the target, while exercise_1.c is the prerequisite.
# It should be noted that $^ represents all the prerequisite.

all: exercise_1 exercise_2 exercise_3 exercise_4 exercise_5 exercise_6 exercise_7 exercise_8 exercise_9 exercise_10 exercise_11 exercise_12 exercise_13 exercise_14 exercise_15 exercise_16 exercise_17 exercise_18 exercise_19 exercise_20 exercise_21 exercise_22

exercise_1: exercise_1.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_2: exercise_2.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_3: exercise_3.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_4: exercise_4.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_5: exercise_5.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_6: exercise_6.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_7: exercise_7.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_8: exercise_8.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_9: exercise_9.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_10: exercise_10.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_11: exercise_11.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_12: exercise_12.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_13: exercise_13.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_14: exercise_14.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_15: exercise_15.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_16: exercise_16.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_17: exercise_17.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_18: exercise_18.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_19: exercise_19.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_20: exercise_20.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_21: exercise_21.c 
	$(CC) $(CFLAGS) -o $@ $< 

exercise_22: exercise_22.c 
	$(CC) $(CFLAGS) -o $@ $< 

clean:
	rm exercise_1 exercise_2 exercise_3 exercise_4 exercise_5 exercise_6 exercise_7 exercise_8 exercise_9 exercise_10 exercise_11 exercise_12 exercise_13 exercise_14 exercise_15 exercise_16 exercise_17 exercise_18 exercise_19 exercise_20 exercise_21 exercise_22
