all: exercise_1 exercise_2 exercise_15

exercise_1:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_1 exercise_1.c

exercise_2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_2 exercise_2.c

exercise_15:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_15 exercise_15.c

clean:
	rm exercise_1 exercise_2 exercise_15
