all: reverse repdigit interest

reverse:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o reverse reverse.c

repdigit:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o repdigit repdigit.c

interest:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o interest interest.c

clean:
	rm reverse repdigit interest
