all: exercise_1 exercise_2 exercise_3 exercise_4 exercise_5 exercise_6 exercise_10 exercise_11 exercise_12 exercise_13 exercise_18 exercise_19

exercise_1:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_1 exercise_1.c

exercise_2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_2 exercise_2.c

exercise_3:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_3 exercise_3.c

exercise_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_4 exercise_4.c

exercise_5:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_5 exercise_5.c

exercise_6:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_6 exercise_6.c

exercise_10:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_10 exercise_10.c

exercise_11:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_11 exercise_11.c

exercise_12:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_12 exercise_12.c

exercise_13:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_13 exercise_13.c

exercise_18:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_18 exercise_18.c

exercise_19:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_19 exercise_19.c

clean:
	rm exercise_1 exercise_2 exercise_3 exercise_4 exercise_5 exercise_6 exercise_10 exercise_11 exercise_12 exercise_13 exercise_18 exercise_19
