all: project_1 project_2 project_3 project_4 project_5 project_6 project_7 project_8

project_1:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_1 project_1.c

project_2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_2 project_2.c

project_3:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_3 project_3.c

project_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_4 project_4.c

project_5:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_5 project_5.c

project_6:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_6 project_6.c

project_7:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_7 project_7.c

project_8:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_8 project_8.c

clean:
	rm project_1 project_2 project_3 project_4 project_5 project_6 project_7 project_8
