exercise_4: exercise_4.o
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_4 exercise_4.o

exercise_4.o: exercise_4.c debug.h 
	gcc -O -Wall -W -pedantic -ansi -std=c99 -c exercise_4.c

clean:
	rm exercise_4
