all: exercise_4 exercise_6 exercise_7 exercise_8 exercise_9 exercise_10 exercise_11 exercise_12 exercise_13 exercise_14 exercise_15 exercise_16 exercise_17 exercise_18

exercise_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_4 exercise_4.c

exercise_6:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_6 exercise_6.c

exercise_7:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_7 exercise_7.c

exercise_8:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_8 exercise_8.c

exercise_9:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_9 exercise_9.c

exercise_10:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_10 exercise_10.c

exercise_11:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_11 exercise_11.c

exercise_12:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_12 exercise_12.c

exercise_13:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_13 exercise_13.c

exercise_14:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_14 exercise_14.c

exercise_15:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_15 exercise_15.c

exercise_16:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_16 exercise_16.c

exercise_17:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_17 exercise_17.c

exercise_18:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o exercise_18 exercise_18.c

clean:
	rm exercise_4 exercise_6 exercise_7 exercise_8 exercise_9 exercise_10 exercise_11 exercise_12 exercise_13 exercise_14 exercise_15 exercise_16 exercise_17 exercise_18
