all: average countdown pun2 prime

average:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o average average.c

countdown:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o countdown countdown.c

pun2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o pun2 pun2.c

prime:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o prime prime.c

clean:
	rm average countdown pun2 prime
