all: project_1 project_2 project_3 project_4

project_1:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_1 project_1.c

project_2:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_2 project_2.c

project_3:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_3 project_3.c

project_4:
	gcc -O -Wall -W -pedantic -ansi -std=c99 -o project_4 project_4.c

clean:
	rm project_1 project_2 project_3 project_4
