CC=gcc
CFLAGS=-O -Wall -W -pedantic -ansi -std=c99

all: project_1 project_5 project_6

project_1: project_1.c
	$(CC) $(CFLAGS) -o $@ $<

project_5: project_5.c
	$(CC) $(CFLAGS) -o $@ $<

project_6: project_6.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm project_1 project_5 project_6
